language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: 
  - pip3 install .
  - pip3 install simpy
  - pip3 install codecov
script:
  - python3 examples/bank.py
  - python3 examples/boarding.py
  - python3 examples/fish.py
  - python3 examples/pallet_norestart.py
  - python3 examples/pallet_restart.py
  - python3 examples/supermarket.py
  - coverage run tests/all.py
after_success:
  - codecov
