language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - pip install .
  - pip install simpy
  - pip install codecov
script:
  - python3 examples/bank.py
  - python3 examples/boarding.py
  - python3 examples/fish.py
  - python3 examples/pallet_norestart.py
  - python3 examples/pallet_restart.py
  - python3 examples/supermarket.py
  - coverage run tests/all.py
after_success:
  - codecov
