language: python
python:
  - "3.4"
install: 
  - pip install .
  - pip install simpy
  - pip install codecov
script:
  - coverage run examples/simple.py
  - coverage run examples/splitter.py
  - coverage run examples/supermarket.py
after_success:
  - codecov
