language: python
python:
  - "3.4"
install: 
  - pip install .
  - pip install simpy
  - pip install codecov
script:
  - python3 examples/simple.py
  - python3 examples/splitter.py
  - python3 examples/supermarket.py
  - coverage run test/all.py
after_success:
  - codecov
