language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - pip install .
  - pip install simpy
  - pip install codecov
script:
  - python3 examples/simple.py
  - python3 examples/splitter.py
  - python3 examples/supermarket.py
  - coverage run tests/all.py
after_success:
  - codecov
