language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: 
  - pip install .
  - pip install simpy
  - pip install codecov
script:
  - python3 examples/basic.py
  - python3 examples/preemption_norestart.py
  - python3 examples/preemption_restart.py
  - python3 examples/priority.py
  - python3 examples/renege.py
  - python3 examples/splitter.py
  - coverage run tests/all.py
after_success:
  - codecov
